---
- name: Prepare CryptoLib dependencies for Debian
  become: yes
  when: ansible_facts['os_family'] == "Debian"
  block:
    - name: Enable i386 architecture
      command: dpkg --add-architecture i386
    - name: Update apt package cache
      apt: update_cache=yes
      tags: base
    - name: Include OS specific variables Debian
      include_vars:
        file: "Debian.yml"
        name: cryptovars
      tags: base
- name: Prepare CryptoLib dependencies for RedHat
  become: yes
  when: (ansible_facts['os_family'] == "RedHat") or (ansible_facts['os_family'] == "Rocky")
  block:
    - name: Include OS specific variables RedHat / Rocky
      include_vars:
        file: "RedHat.yml"
        name: cryptovars
      tags: base
- name: Install CryptoLib dependencies
  become: yes
  package:
    state: latest
    name: "{{ cryptovars.packages_to_install }}"
  tags: base

# CryptoLib PIP3 Depenencies
- name: PIP install pycryptodome
  become: yes
  pip: 
    name: pycryptodome
    state: latest
  tags: pycryptodome

# WolfSSL Builds
- name: WolfSSL
  become: yes
  block:
    - name: Clean wolfssl path
      file:
        state: absent
        path: /tmp/wolfssl
    - name: Git checkout wolfssl
      ansible.builtin.git:
        repo: 'https://github.com/wolfSSL/wolfssl.git'
        dest: /tmp/wolfssl
        version: v5.6.0-stable
    - name: WolfSSL Autogen
      shell: |
        cd /tmp/wolfssl
        ./autogen.sh
    - name: Create a wolfssl build directory
      ansible.builtin.file:
        path: /tmp/wolfssl/build
        state: directory
        mode: '0755'
    - name: WolfSSL build
      shell: |
        cd /tmp/wolfssl/build
        ../configure
        make 
        make install
    - name: Create a wolfssl build32 directory
      ansible.builtin.file:
        path: /tmp/wolfssl/build32
        state: directory
        mode: '0755'
    - name: WolfSSL 32-bit build
      shell: |
        cd /tmp/wolfssl/build32
        export CFLAGS="-m32"
        ../configure
        make 
        make install

# CryptoLib 32-bit Packages
- name: Install CryptoLib 32-bit dependencies for Debian
  become: yes
  when: ansible_facts['os_family'] == "Debian"
  block:
    - name: Download debian files
      command: apt-get download libgcrypt20-dev:i386 libgpg-error-dev:i386
      args:
        chdir: /tmp/
    - name: Force install 32-bit debian files
      command: dpkg --force-all -i /tmp/libgcrypt20-dev_1.8.5-5ubuntu1.1_i386.deb /tmp/libgpg-error-dev_1.37-1_i386.deb
