---
# Get  42 installed
- name: Clone 42 repo
  become: yes
  git:
    dest: '/opt/nos3/42'
    repo: 'https://github.com/ericstoneking/42.git'
    version: bb9d25d5767ea2df3e4c74736252e70d8c845b77
    update: no
- name:  Change 42 build
  become: yes
  block:
  - name:  Compile 42 as 32 bit
    replace:
      path: /opt/nos3/42/Makefile
      regexp: 'ARCHFLAG =\s*$'
      replace: 'ARCHFLAG = -m32'
  - name:  Link 42 as 32 bit
    replace:
      path: /opt/nos3/42/Makefile
      regexp: 'LFLAGS = -L'
      replace: 'LFLAGS = -m32 -L'
- name: Build 42
  become: yes
  make:
    chdir: /opt/nos3/42
- name:  Change 42 directory ownership
  become: yes
  file:
    path: '/opt/nos3/42'
    state: directory
    recurse: yes
    owner: nos3
    group: nos3
