---

- name: AIT - clone {{ait.repo}}
  become: yes
  become_user: nos3
  git:
    repo: 'https://github.com/NASA-AMMOS/{{ait.repo}}'
    dest: '/home/nos3/AIT/{{ait.repo}}'
    version: '{{ait.version}}'

- name: AIT - Install via pip {{ait.repo}} package into venv {{ait.venv}}
  become: yes
  become_user: nos3
  pip:
    name: '/home/nos3/AIT/{{ait.repo}}'
    virtualenv: '/home/nos3/.virtualenvs/{{ait.venv}}'

