---
- name: Display ground variable
  debug:
    var: GROUND

# cosmos
- name: COSMOS
  when: (GROUND == "COSMOS") or (GROUND == "BOTH")
  block:
  - name: Install COSMOS on Ubuntu
    become: yes
    when: ansible_facts['os_family'] == "Debian"
    block:
    - name: Install ruby-termios gem
      gem:
        name: ruby-termios
        user_install: no
        include_doc: no
    - name: Install rake gem on Ubuntu
      shell:
        cmd: gem install rake --no-ri --no-rdoc
    - name: Install cosmos gem
      become: yes
      shell:
        cmd: gem install -v 4.5.2 cosmos --no-ri --no-rdoc
  - name: Install COSMOS on CentOS # Ugg... this is soooo... ugly!
    become: yes
    when: ansible_facts['os_family'] == "RedHat"
    block:
    - name: Install GPG key for rvm
      shell:
        cmd: gpg --keyserver hkp://pool.sks-keyservers.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB
    - name: Retrieve rvm
      get_url:
        url: https://get.rvm.io
        dest: /root/rvm-install.sh
    - name: Install rvm
      shell:
        cmd: bash /root/rvm-install.sh stable
    - name: Install ruby 2.4.2
      shell:
        cmd: bash -c 'source /etc/profile.d/rvm.sh; rvm install 2.4.2'
    - name: Make ruby 2.4.2 default
      shell:
        cmd: bash -c 'source /etc/profile.d/rvm.sh; rvm use 2.4.2 --default'
    - name: Install cosmos gem
      become: yes
      shell:
        cmd: bash -c 'source /etc/profile.d/rvm.sh; gem install cosmos --no-ri --no-rdoc'

# AIT
- name: AIT
  when: ((GROUND == "AIT") or (GROUND == "BOTH")) and (ansible_facts['os_family'] == "Debian")
  tags: config
  block:
    - name: AIT - Run apt-get update
      become: yes
      apt: update_cache=yes
  
    - name: AIT - Install AIT Required Packages
      become: yes
      package:
        state: present
        name:
          - git
          - git-gui
          - gitk
          - virtualenv
          - virtualenvwrapper
      
    - name: AIT - Install python setup-tools 
      become: yes
      apt: name=python-setuptools
        
    - name: AIT - Install virtualenvwrapper via pip
      pip: name=virtualenvwrapper
      
    - name: AIT - Update bashrc for virtualenvwrapper
      become: yes
      become_user: nos3
      blockinfile:
        path: /home/nos3/.bashrc
        block: |
          export WORKON_HOME=/home/nos3/.virtualenvs
          export PROJECT_HOME=/home/nos3/Devel
     
    - name: AIT - Set up ait virtualenv directory
      become: yes
      become_user: nos3
      file:
        path: /home/nos3/.virtualenvs
        state: directory
        owner: nos3
        group: nos3
        mode: 0755
      
    - name: AIT - Copy virtualenvwrapper postactivate
      become: yes
      become_user: nos3
      copy:
        src: /vagrant/nos3_filestore/ait/postactivate
        dest: /home/nos3/.virtualenvs/postactivate
        owner: nos3
        group: nos3
        mode: 0644
      
    - name: AIT - Set up virtualenvs
      become: yes
      become_user: nos3
      include: install_ait_repo.yml ait={{item}}
      loop:
        - repo: AIT-Core
          version: 2.0.0
          venv: ait
        - repo: AIT-GUI
          version: 2.1.0
          venv: ait
        - repo: AIT-Core
          version: 2.0.0
          venv: ait-cfs
        - repo: AIT-GUI
          version: 2.1.0
          venv: ait-cfs
        - repo: AIT-CFS
          version: HEAD
          venv: ait-cfs     
       
    # Copy AIT Config files
    - name: AIT - Copy AIT Config Files
      become: yes
      become_user: nos3
      copy:
        src: /vagrant/nos3_filestore/ait/config/
        dest: /home/nos3/AIT/AIT-CFS/config
        owner: nos3
        group: nos3
        mode: 0644
    
    # Copy AIT GUI Files
    - name: AIT - Copy AIT GUI Files
      become: yes
      become_user: nos3
      copy:
        src: /vagrant/nos3_filestore/ait/gui/
        dest: /home/nos3/AIT/AIT-CFS/gui
        owner: nos3
        group: nos3
        mode: 0644
