---
# Figure out if ground is COSMOS, AIT, or both.  Then figure out how to get config set up (e.g. cosmos install cosmos) and populated with command, telemetry, and other tool dfn for the mission

- name: Install cosmos on Ubuntu
  when: ((GROUND == "COSMOS") or (GROUND == "BOTH")) and (ansible_facts['os_family'] == "Debian")
  become: yes
  become_user: nos3
  shell:
    chdir: /home/nos3
    cmd: cosmos install cosmos
  tags: config
- name: Install cosmos on CentOS
  when: ((GROUND == "COSMOS") or (GROUND == "BOTH")) and (ansible_facts['os_family'] == "RedHat")
  become: yes
  become_user: nos3
  shell:
    chdir: /home/nos3
    cmd: bash -c 'source /etc/profile.d/rvm.sh; cosmos install cosmos'
  tags: config

- name: Set up Command and Control mission configuration
  debug:
    msg: TODO - Set up Command and Control mission configuration
  tags: config
