# Playbook to create a NOS3 development machine
- hosts: all-roles
  roles:
    - role: nos3-software-env
    - role: nos3-user
    - role: nos3-42 # 42
    - role: nos3-ground # COSMOS and/or AIT 
    - role: nos3-ground-mission-config # COSMOS, AIT mission specific config files
