# Playbook to create a NOS3 development machine
- hosts: dev
  roles:
    - role: nos3-software-env
    - role: nos3-user
    - role: nos3-user-vm
    - role: nos3-ground # COSMOS and/or AIT 
    - role: nos3-42 # 42
    