---
- name: Set up 42 InOut mission configuration # copy from git repo checkout location?
  become: yes
  become_user: nos3
  file:
    path: /home/nos3/nos3-42
    state: directory
  tags: config
- name: Symlink the 42 Model directory
  become: yes
  file:
    src: /opt/42/Model
    dest: /home/nos3/nos3-42/Model
    state: link
  tags: config
- name: Symlink the 42 World directory
  become: yes
  file:
    src: /opt/42/World
    dest: /home/nos3/nos3-42/World
    state: link
  tags: config
- name: Symlink the 42 Kit directory
  become: yes
  file:
    src: /opt/42/Kit
    dest: /home/nos3/nos3-42/Kit
    state: link
  tags: config

- name:  TODO - finish
  debug:
    msg: TODO - Set up 42 InOut mission configuration
  tags: config
